// <auto-generated>
// This code was generated by T4 template. Do not change this code.
// </auto-generated>
using System;

namespace Kzrnm.Competitive.IO
{
    using MI = System.Runtime.CompilerServices.MethodImplAttribute;
    /// <summary>
    /// Calls <see cref="ConsoleReader"/> several times
    /// </summary>
    public class RepeatReader<R> where R : ConsoleReader
    {
        internal readonly R cr;
        internal readonly int count;
        /// <summary>
        /// Initialize <see cref="RepeatReader{R}"/>
        /// </summary>
        [MI(256)]
        public RepeatReader(R cr, int count)
        {
            this.cr = cr; this.count = count;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.Ascii"/> array
        /// </summary>
        [MI(256)]
        public string[] Ascii() => Read<string>();
        /// <summary>
        /// Read <see cref="ConsoleReader.Int"/> array
        /// </summary>
        [MI(256)]
        public int[] Int() => Read<int>();
        /// <summary>
        /// Read <see cref="ConsoleReader.UInt"/> array
        /// </summary>
        [MI(256)]
        public uint[] UInt() => Read<uint>();
        /// <summary>
        /// Read <see cref="ConsoleReader.Long"/> array
        /// </summary>
        [MI(256)]
        public long[] Long() => Read<long>();
        /// <summary>
        /// Read <see cref="ConsoleReader.ULong"/> array
        /// </summary>
        [MI(256)]
        public ulong[] ULong() => Read<ulong>();
        /// <summary>
        /// Read <see cref="ConsoleReader.Double"/> array
        /// </summary>
        [MI(256)]
        public double[] Double() => Read<double>();

        /// <summary>
        /// Read <see cref="ConsoleReader.Decimal"/> array
        /// </summary>
        [MI(256)]
        public decimal[] Decimal() => Read<decimal>();

        /// <summary>
        /// Read <see cref="ConsoleReader.Line"/> array
        /// </summary>
        [MI(256)]
        public string[] Line()
        {
            var arr = new string[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.Line();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.String"/> array
        /// </summary>
        [MI(256)]
        public string[] String()
        {
            var arr = new string[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.String();
            return arr;
        }

        /// <summary>
        /// Read <see cref="ConsoleReader.Int0"/> array
        /// </summary>
        [MI(256)]
        public int[] Int0()
        {
            var arr = new int[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.Int0();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.UInt0"/> array
        /// </summary>
        [MI(256)]
        public uint[] UInt0()
        {
            var arr = new uint[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.UInt0();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.Long0"/> array
        /// </summary>
        [MI(256)]
        public long[] Long0()
        {
            var arr = new long[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.Long0();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.ULong0"/> array
        /// </summary>
        [MI(256)]
        public ulong[] ULong0()
        {
            var arr = new ulong[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.ULong0();
            return arr;
        }

        /// <summary>
        /// implicit call <see cref="Read"/>
        /// </summary>
        [MI(256)] public static implicit operator string[](RepeatReader<R> rr) => rr.Read<string>();
        /// <summary>
        /// implicit call <see cref="Read"/>
        /// </summary>
        [MI(256)] public static implicit operator int[](RepeatReader<R> rr) => rr.Read<int>();
        /// <summary>
        /// implicit call <see cref="Read"/>
        /// </summary>
        [MI(256)] public static implicit operator uint[](RepeatReader<R> rr) => rr.Read<uint>();
        /// <summary>
        /// implicit call <see cref="Read"/>
        /// </summary>
        [MI(256)] public static implicit operator long[](RepeatReader<R> rr) => rr.Read<long>();
        /// <summary>
        /// implicit call <see cref="Read"/>
        /// </summary>
        [MI(256)] public static implicit operator ulong[](RepeatReader<R> rr) => rr.Read<ulong>();
        /// <summary>
        /// implicit call <see cref="Read"/>
        /// </summary>
        [MI(256)] public static implicit operator double[](RepeatReader<R> rr) => rr.Double();
        /// <summary>
        /// implicit call <see cref="Read"/>
        /// </summary>
        [MI(256)] public static implicit operator decimal[](RepeatReader<R> rr) => rr.Decimal();

        /// <summary>
        /// Get array of <typeparamref name="T"/>.
        /// </summary>
        public T[] Read<T>()
        {
            var arr = new T[count];
            for (int i = 0; i < arr.Length; i++)
                arr[i] = cr.Read<T>();
            return arr;
        }

        /// <summary>
        /// Repeat <paramref name="factory"/>()
        /// </summary>
        [MI(256)]
        public T[] Select<T>(Func<ConsoleReader, T> factory)
        {
            var c = count;
            var arr = new T[c];
            for (var i = 0; i < c; i++)
                arr[i] = factory(cr);
            return arr;
        }
        /// <summary>
        /// Repeat <paramref name="factory"/>()
        /// </summary>
        [MI(256)]
        public T[] Select<T>(Func<ConsoleReader, int, T> factory)
        {
            var c = count;
            var arr = new T[c];
            for (var i = 0; i < c; i++)
                arr[i] = factory(cr, i);
            return arr;
        }
    }
    /// <summary>
    /// Defines extension
    /// </summary>
    public static class RepeatEx
    {
        /// <summary>
        /// Get <see cref="RepeatReader{R}"/>
        /// </summary>
        [MI(256)] public static RepeatReader<ConsoleReader> Repeat(this ConsoleReader cr, int count)  => new RepeatReader<ConsoleReader>(cr, count);
    }
}
