// <auto-generated>
// This code was generated by T4 template. Do not change this code.
// </auto-generated>
using System;

namespace Kzrnm.Competitive.IO
{
    using _R = RepeatReader;
    using MI = System.Runtime.CompilerServices.MethodImplAttribute;
    /// <summary>
    /// Calls <see cref="ConsoleReader"/> several times
    /// </summary>
    public struct RepeatReader
    {
        internal readonly ConsoleReader cr;
        internal readonly int count;
        [MI(256)]
        internal RepeatReader(ConsoleReader cr, int count)
        {
            this.cr = cr; this.count = count;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.Line"/> array
        /// </summary>
        [MI(256)]
        public string[] Line()
        {
            var arr = new string[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.Line();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.String"/> array
        /// </summary>
        [MI(256)]
        public string[] String()
        {
            var arr = new string[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.String();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.Ascii"/> array
        /// </summary>
        [MI(256)]
        public string[] Ascii()
        {
            var arr = new string[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.Ascii();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.Int"/> array
        /// </summary>
        [MI(256)]
        public int[] Int()
        {
            var arr = new int[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.Int();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.Int0"/> array
        /// </summary>
        [MI(256)]
        public int[] Int0()
        {
            var arr = new int[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.Int0();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.UInt"/> array
        /// </summary>
        [MI(256)]
        public uint[] UInt()
        {
            var arr = new uint[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.UInt();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.UInt0"/> array
        /// </summary>
        [MI(256)]
        public uint[] UInt0()
        {
            var arr = new uint[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.UInt0();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.Long"/> array
        /// </summary>
        [MI(256)]
        public long[] Long()
        {
            var arr = new long[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.Long();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.Long0"/> array
        /// </summary>
        [MI(256)]
        public long[] Long0()
        {
            var arr = new long[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.Long0();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.ULong"/> array
        /// </summary>
        [MI(256)]
        public ulong[] ULong()
        {
            var arr = new ulong[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.ULong();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.ULong0"/> array
        /// </summary>
        [MI(256)]
        public ulong[] ULong0()
        {
            var arr = new ulong[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.ULong0();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.Double"/> array
        /// </summary>
        [MI(256)]
        public double[] Double()
        {
            var arr = new double[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.Double();
            return arr;
        }
        /// <summary>
        /// Read <see cref="ConsoleReader.Decimal"/> array
        /// </summary>
        [MI(256)]
        public decimal[] Decimal()
        {
            var arr = new decimal[count];
            for (var i = 0; i < count; i++)
                arr[i] = cr.Decimal();
            return arr;
        }

        /// <summary>
        /// implicit call <see cref="RepeatReader.Ascii()"/>
        /// </summary>
        [MI(256)] public static implicit operator string[](_R rr) => rr.Ascii();
        /// <summary>
        /// implicit call <see cref="RepeatReader.Int()"/>
        /// </summary>
        [MI(256)] public static implicit operator int[](_R rr) => rr.Int();
        /// <summary>
        /// implicit call <see cref="RepeatReader.UInt()"/>
        /// </summary>
        [MI(256)] public static implicit operator uint[](_R rr) => rr.UInt();
        /// <summary>
        /// implicit call <see cref="RepeatReader.Long()"/>
        /// </summary>
        [MI(256)] public static implicit operator long[](_R rr) => rr.Long();
        /// <summary>
        /// implicit call <see cref="RepeatReader.ULong()"/>
        /// </summary>
        [MI(256)] public static implicit operator ulong[](_R rr) => rr.ULong();
        /// <summary>
        /// implicit call <see cref="RepeatReader.Double()"/>
        /// </summary>
        [MI(256)] public static implicit operator double[](_R rr) => rr.Double();
        /// <summary>
        /// implicit call <see cref="RepeatReader.Decimal()"/>
        /// </summary>
        [MI(256)] public static implicit operator decimal[](_R rr) => rr.Decimal();
    }
    /// <summary>
    /// Defines extension
    /// </summary>
    public static class RepeatEx
    {
        /// <summary>
        /// Get <see cref="RepeatReader"/>
        /// </summary>
        [MI(256)] public static _R Repeat(this ConsoleReader cr, int count) => new _R(cr, count);
    }
}
