name: test

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: 

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  WORKFLOW_BUILD_SLN: Competitive.IO.sln

jobs:
  test:
    uses: kzrnm/dotnet-actions/.github/workflows/unittest.yml@v2
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    with:
      target: Competitive.IO.sln
      os: ${{matrix.os}}
      dotnet-version: |
        8.0.x
        7.0.x
        6.0.x
        3.1.x
      test-logger: GitHubActions
